name: depth-hpc
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.4.1
  - torchvision=0.19.1
  - torchaudio=2.4.1
  - pytorch-cuda=12.1
  - pip:
      - numpy<2
      - scipy
      - pandas
      - matplotlib
      - tqdm
      - pyyaml
      - pillow
      - h5py
      - scikit-learn
      - scikit-image
      - tensorboard
      - jupyter
      - ipykernel
      - opencv-python-headless==4.10.0.84
      - timm
      - einops
      - safetensors